name: digitaltwinv1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - blas=1.0
  - ca-certificates
  - certifi
  - cffi
  - et_xmlfile
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipopt
  - libblas
  - libffi
  - liblapack
  - llvm-meta
  - llvmlite
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msys2-conda-epoch
  - metis
  - numpy
  - numpy-base
  - openmp
  - openpyxl
  - openssl
  - ply
  - pyomo
  - python_abi
  - setuptools
  - sqlite
  - tbb
  - typing-extensions
  - typing_extensions
  - ucrt
  - vc
  - vc14_runtime
  - vs2015_runtime
  - wheel
  - zipp
  - zlib
  - pip:
      - absl-py==2.1.0
      - alabaster==0.7.13
      - attrs==24.2.0
      - babel==2.16.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.1.1
      - cryptography==43.0.1
      - cycler==0.12.1
      - deepdiff==8.0.1
      - docutils==0.20.1
      - exceptiongroup==1.2.2
      - execnet==2.1.1
      - fiona==1.10.1
      - fonttools==4.54.1
      - geojson==3.1.0
      - geopandas==0.13.2
      - gurobipy==11.0.3
      - idna==3.10
      - igraph==0.11.6
      - imagesize==1.4.1
      - immutabledict==4.2.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - lightsim2grid==0.8.2
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matpowercaseframes==1.0.11
      - networkx==3.1
      - numpydoc==1.7.0
      - orderly-set==5.2.2
      - ortools==9.11.4210
      - pandapower==2.13.1
      - pandas==2.0.3
      - pillow==10.4.0
      - plotly==5.24.1
      - pluggy==1.5.0
      - power-grid-model==1.6.48
      - power-grid-model-io==1.2.57
      - protobuf==5.26.1
      - psycopg2==2.9.9
      - pycparser==2.22
      - pyparsing==3.1.4
      - pyproj==3.5.0
      - pytest==8.3.3
      - pytest-xdist==3.6.1
      - python-calamine==0.2.3
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - scipy==1.10.1
      - shapely==2.0.6
      - snowballstemmer==2.2.0
      - sphinx==7.1.2
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - structlog==24.4.0
      - tabulate==0.9.0
      - tenacity==9.0.0
      - texttable==1.7.0
      - tomli==2.0.1
      - tqdm==4.66.5
      - tzdata==2024.2
      - urllib3==2.2.3
      - xlsxwriter==3.2.0
